#!/usr/bin/env node
'use strict';

var vipp = require('./src/main');
var fs = require('fs');
var syscall = require('child_process').execSync;

function main() {
	// Parse args
	var args = process.argv.slice(2);
	var filename = args[0];
	if (filename === undefined) {
		console.log('usage: vipp filename');
		return;
	}
	// Invoke make, to be sure that everything is up-to-date
	syscall('make', {stdio: null});
	// Run the thing
	var code = fs.readFileSync(filename);
	var fn = vipp.compile(code);
	console.log(fn());
}

main();