#!/usr/bin/env node
'use strict';

var fs = require('fs');
var sweet = require('sweet.js');


var macroFilename = './src/ad/macros.js';
function transform(filename) {
	var macrosContents = fs.readFileSync(macroFilename);
	var fileContents = fs.readFileSync(filename);
	var fullContents = macrosContents + '\n' + fileContents;
	var compiled = sweet.compile(fullContents);
	console.log(compiled.code);
}


// AD-ify one file
function main() {
	var args = process.argv.slice(2);
	var filename = args[0];
	if (filename === undefined) {
		console.log('usage: transform filename');
		return;
	}
	transform(filename);
}

main();