#!/usr/bin/env node
'use strict';

var fs = require('fs');
var adtransform = require('src/ad/transform.js').transform

// AD-ify one file
function main() {
	var args = process.argv.slice(2);
	var filename = args[0];
	if (filename === undefined) {
		console.log('usage: transform filename');
		return;
	}
	var code = fs.readFileSync(filename);
	console.log(adtransform(code));
}

main();